Updated LE script to 0.9.7 (#258)
* Removed unused python modules datetime and sys

* Fixed python exception "has no attribute decode"

AttributeError: \'str\' object has no attribute \'decode\

* Fixed overwrite_vs parsing

* Updated parm description, more debug, imports

* Increased version to 0.9.7

* Added prefix to debug messages